baseURL = "https://nicoayci.github.io/cheveuxguide"
publishDir = "docs"
title = "Le guide des cheveux"
theme = "etch"
languageCode = "fr-FR"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Tout savoir pour garder ses cheveux"
  copyright = "copyright"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "articles"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "a propos"
    url = "/a-propos/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

